display_name: Yundo
publisher_display_name: Yundo
identity_name: Yundo.Yundo
msix_version: 1.0.0.10004
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: ar, en-us, es-es, fa-ir, fr-fr, id-id, pt-br, ru-ru, tr-tr, zh-cn, zh-tw
protocol_activation: yundo
execution_alias: yundo
certificate_path: windows\sign.pfx
certificate_password:
publisher: CN=8CB43675-F44B-4AA5-9372-E8727781BDC4
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart

# For testing with a self-signed certificate
# publisher: CN=Yundo-Test
# certificate_password: "1234"
# install_certificate: "true"
