title: Yundo
background: "background.png"
window:
  size:
    width: 600
    height: 328
contents:
  - x: 440
    y: 190
    type: link
    path: "/Applications"
  - x: 160
    y: 190
    type: file
    path: Yundo.app
