display_name: Yundo
package_name: yundo
maintainer:
  name: Yundo
  email: support@yundo.app

priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/images/source/ic_launcher_border.png

# Post-installation tasks:
# 1. Inject StartupWMClass into the system .desktop file for correct icon association
# 2. Remove conflicting hiddify.desktop files from users' .local directories (cleanup AppImage artifacts)
# 3. Update the desktop database to apply changes immediately
postinstall_scripts:
  - echo "Setting up Yundo..."
  - sudo sed -i '/^\[Desktop Entry\]/a StartupWMClass=app.yundo.client' "/usr/share/applications/yundo.desktop"
  - echo "Search and remove yundo.desktop from .local"
  - for user_dir in /home/*; do if [ -f "$user_dir/.local/share/applications/yundo.desktop" ]; then rm -f "$user_dir/.local/share/applications/yundo.desktop"; echo "Found and removed yundo.desktop from $user_dir .local"; fi; done
  - update-desktop-database /usr/share/applications
  - echo "Yundo is ready to use :)"

# Post-uninstallation tasks:
# 1. Iterate through all user directories to remove Hiddify configuration and data
# 2. Clean up root user data to ensure a clean removal
postuninstall_scripts:
  - echo "Removing Yundo user data..."
  - for user_dir in /home/*; do if [ -d "$user_dir/.local/share/yundo" ]; then rm -rf "$user_dir/.local/share/yundo"; echo "Removed data from $user_dir"; fi; done
  - rm -rf /root/.local/share/yundo
  - echo "Yundo data cleanup complete."

keywords:
  - Yundo
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: Yundo

categories:
  - Network

startup_notify: true
# app_links setup for Linux
# https://github.com/llfbandit/app_links/blob/master/doc/README_linux.md
supported_mime_type:
  - x-scheme-handler/yundo
  - x-scheme-handler/v2ray
  - x-scheme-handler/v2rayn
  - x-scheme-handler/v2rayng
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/sing-box

metainfo: linux/packaging/app.yundo.client.appdata.xml
