app_id: 4F3D5D2F-40B8-45AB-934E-2B8C8C58D50A
publisher: Yundo
publisher_url: https://github.com/yundoapp/nimbus-client
display_name: Yundo
create_desktop_icon: true
install_dir_name: "{autopf64}\\Yundo"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
