import 'package:flutter_test/flutter_test.dart';
import 'package:hiddify/features/nimbus/route_history/model/nimbus_route_history.dart';
import 'package:hiddify/features/nimbus/route_history/notifier/nimbus_route_history_notifier.dart';

void main() {
  group('Nimbus route history controller', () {
    test('uses the loopback controller and secret generated by the core', () {
      final config = parseNimbusRouteHistoryControllerConfig('''
        {
          "experimental": {
            "clash_api": {
              "external_controller": "127.0.0.1:16756",
              "secret": "local-secret"
            }
          }
        }
      ''');

      expect(config, isNotNull);
      expect(config!.webSocketUri.toString(), 'ws://127.0.0.1:16756/connections');
      expect(config.headers, {'Authorization': 'Bearer local-secret'});
    });

    test('rejects a non-loopback controller', () {
      final config = parseNimbusRouteHistoryControllerConfig('''
        {
          "experimental": {
            "clash_api": {
              "external_controller": "192.0.2.10:16756",
              "secret": "local-secret"
            }
          }
        }
      ''');

      expect(config, isNull);
    });

    test('returns null for missing or malformed core config', () {
      expect(parseNimbusRouteHistoryControllerConfig('{}'), isNull);
      expect(parseNimbusRouteHistoryControllerConfig('{'), isNull);
    });
  });

  test('parses a live core connection snapshot into an acceleration record', () {
    final observedAt = DateTime(2026, 8, 3, 12);
    final entries = mergeNimbusRouteHistory(
      previous: const [],
      observedAt: observedAt,
      snapshot: [
        {
          'id': 'connection-1',
          'metadata': {'host': 'servicewechat.com', 'destinationIP': '', 'destinationPort': '443', 'network': 'tcp'},
          'rule': 'final',
          'rulePayload': '',
          'chains': ['nimbus-proxy', 'select'],
          'start': '2026-08-03T04:00:00Z',
        },
      ],
    );

    expect(entries, hasLength(1));
    expect(entries.single.target, 'servicewechat.com');
    expect(entries.single.decision, NimbusRouteDecision.accelerated);
    expect(entries.single.isActive, isTrue);
  });

  test('recognizes the Hiddify native direct outbound as direct access', () {
    final entry = parseNimbusRouteHistoryEntry({
      'id': 'connection-direct',
      'metadata': {'host': 'rawya.ai', 'destinationPort': '443', 'network': 'tcp'},
      'rule': 'DomainSuffix',
      'rulePayload': 'rawya.ai',
      'chains': ['direct \u00a7hide\u00a7'],
    }, observedAt: DateTime(2026, 8, 3, 12));

    expect(entry, isNotNull);
    expect(entry!.decision, NimbusRouteDecision.direct);
  });

  test('recognizes the macOS helper direct outbound as direct access', () {
    final entry = parseNimbusRouteHistoryEntry({
      'id': 'connection-helper-direct',
      'metadata': {'host': 'baidu.com', 'destinationPort': '443', 'network': 'tcp'},
      'rule': 'domain_suffix=baidu.com => route(yundo-direct)',
      'chains': ['yundo-direct'],
    }, observedAt: DateTime(2026, 8, 3, 12));

    expect(entry, isNotNull);
    expect(entry!.decision, NimbusRouteDecision.direct);
  });
}
